### ISSUE TITLE
myfavoritebeer.org displays 'This site does not supply identity information'

### ISSUE THREAD

**Issue by michielbdejong** [mozilla/browserid_addon#76]
i have made it as far as:
    (mozilla-addon-sdk-582d248)mich@unhosted-one:~/Downloads/mozilla-addon-sdk-582d248/packages/development-mode$ cfx run

and it opens a firefox instance. i visit myfavoritebeer.org with it, but don't see things like in the screencast. instead, myfavoritebeer.org displays 'This site does not supply identity information'

**Comment by michielbdejong** [comment]
right, i re-read the instructions on https://github.com/mozilla/browserid_addon/tree/master/addon and it says "from the sessions directory, do 'cfx run'. so the problem probably is that i was in the packages/development-mode directory instead of in the sessions directory. but there doesn't seem to be a sessions directory in current master...

**Comment by shane-tomlinson** [comment]
Thank you @michiel-unhosted, I have updated the docs.  The correct directory is 'addon'
