### ISSUE TITLE
cookie monster errors whenever bulk clearing cookies.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/browserid_addon#83]

**Comment by shane-tomlinson** [comment]
Originally from: https://bugzilla.mozilla.org/show_bug.cgi?id=684564

**Comment by mykmelez** [comment]
Can this be closed now that you've committed a fix?

**Comment by shane-tomlinson** [comment]
@mykmelez - we have been keeping the bugs in the BrowserID projects open until they are verified in the release.  We have been tagging them "in-dev", and "in-beta," the "in-beta" may not apply here for a while.
